---
kind: Service
apiVersion: v1
metadata:
  name: febe-server-dev
spec:
  type: LoadBalancer
  selector:
    app: febe-server-dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: febe-server-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: febe-server-dev
  template:
    metadata:
      labels:
        app: febe-server-dev
    spec:
      containers:
        - name: febe-server-dev
          image: davidespo/febe-server:0.1.0
          ports:
            - containerPort: 3030
              protocol: TCP
